backend:
  name: git-gateway
  branch: main
  identity_url: "https://association-baraca.asso.st/.netlify/identity"
  gateway_url: "https://association-baraca.asso.st/.netlify/git"
  login: true
  roles: ["admin", "editor"]

media_folder: "img/uploads"
public_folder: "img//uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Titre de l'image", name: "alt-im", widget: "string" }
      - { label: "Date du projet", name: "project-date", widget: "string" }
      - { label: "Lieu", name: "lieu", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }