backend:
  name: git-gateway
  branch: main
  identity_url: "https://association-baraca.asso.st/.netlify/identity"
  gateway_url: "https://association-baraca.asso.st/.netlify/git"
  login: true
  roles: ["admin", "editor"]

media_folder: "img/uploads"
public_folder: "img//uploads"

